<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CleanCodeJN.GenericApis.Abstractions" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="9.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CleanCodeJN.GenericApis.Chat\CleanCodeJN.GenericApis.Chat.csproj" />
    <ProjectReference Include="..\..\..\src\CleanCodeJN.GenericApis.DataGrid\CleanCodeJN.GenericApis.DataGrid.csproj" />
    <ProjectReference Include="..\..\Sample\CleanCodeJN.GenericApis.Sample.Core\CleanCodeJN.GenericApis.Sample.Core.csproj" />
  </ItemGroup>

</Project>
