using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using CleanCodeJN.GenericApis.DataGrid.Models;
using CleanCodeJN.GenericApis.DataGrid.Services;
using Microsoft.AspNetCore.Components;
using MudBlazor;

namespace CleanCodeJN.GenericApis.DataGrid.Components;

/// <summary>
/// A fully generic, server-side MudBlazor table that auto-discovers columns from
/// <typeparamref name="TDto"/> and queries a CleanCodeJN GraphQL endpoint with
/// paging, sorting and global text search.
/// </summary>
/// <typeparam name="TDto">
/// Any DTO class — scalar properties (string, numeric, bool, DateTime, Guid, …) are
/// mapped to columns automatically. Complex and collection properties are skipped.
/// </typeparam>
/// <example>
/// <code>
/// &lt;CCJNDataGrid TDto="CustomerGetDto"
///                  GraphQLEndpoint="https://localhost:5001/graphql"
///                  EntityName="customer"
///                  Title="Customers" /&gt;
/// </code>
/// </example>
public partial class CCJNDataGrid<TDto> where TDto : class
{
    // ── Injected services ─────────────────────────────────────────────────────

    [Inject] private GraphQLDataGridService GraphQLService { get; set; } = default!;

    // ── Required parameters ───────────────────────────────────────────────────

    /// <summary>Full URL of the GraphQL endpoint (e.g. <c>https://api/graphql</c>).</summary>
    [Parameter, EditorRequired] public string GraphQLEndpoint { get; set; } = string.Empty;

    /// <summary>
    /// The lowercase GraphQL query field name generated by
    /// <c>AutoQueryTypeExtensions</c>, i.e. <c>typeof(TEntity).Name.ToLowerInvariant()</c>.
    /// Example: entity <c>Customer</c> → <c>"customer"</c>.
    /// </summary>
    [Parameter, EditorRequired] public string EntityName { get; set; } = string.Empty;

    // ── Optional parameters ───────────────────────────────────────────────────

    /// <summary>Optional heading rendered above the table.</summary>
    [Parameter] public string Title { get; set; } = string.Empty;

    /// <summary>Show a search text field that filters all string columns via GraphQL <c>where</c>.</summary>
    [Parameter] public bool Searchable { get; set; } = true;

    /// <summary>Render the table in dense (compact) mode.</summary>
    [Parameter] public bool Dense { get; set; } = false;

    /// <summary>Render alternating row colours.</summary>
    [Parameter] public bool Striped { get; set; } = true;

    /// <summary>MudPaper elevation for the card wrapping the table.</summary>
    [Parameter] public int Elevation { get; set; } = 2;

    /// <summary>Bearer token forwarded as <c>Authorization: Bearer …</c> header.</summary>
    [Parameter] public string? BearerToken { get; set; }

    /// <summary>
    /// DTO property names to exclude from the auto-generated columns.
    /// Example: <c>new HashSet&lt;string&gt; { "Id", "InternalFlag" }</c>.
    /// </summary>
    [Parameter] public HashSet<string> ExcludedProperties { get; set; } = [];

    /// <summary>Page-size choices shown in the pager footer.</summary>
    [Parameter] public int[] PageSizeOptions { get; set; } = [10, 25, 50, 100];

    /// <summary>
    /// Optional custom column overrides. When provided, replaces the auto-detected columns.
    /// Each entry maps a DTO property name to a custom column header.
    /// </summary>
    [Parameter] public Dictionary<string, string>? ColumnHeaders { get; set; }

    // ── Internal state ────────────────────────────────────────────────────────

    private MudTable<TDto> _table = default!;
    private List<ColumnDefinition<TDto>> _columns = [];
    private string _searchTerm = string.Empty;
    private string _activeSearchTerm = string.Empty;
    private CancellationTokenSource _debounceCts = new();
    private bool _loading;
    private string _errorMessage = string.Empty;

    // Cached delegate — must not be recreated on every render, otherwise MudTable
    // detects a parameter change on each keystroke and fires an unwanted reload.
    private Func<TableState, CancellationToken, Task<TableData<TDto>>> _serverDataDelegate = default!;

    // ── Scalar type whitelist ─────────────────────────────────────────────────

    private static readonly HashSet<Type> ScalarTypes =
    [
        typeof(string),
        typeof(bool),
        typeof(char),
        typeof(byte), typeof(sbyte),
        typeof(short), typeof(ushort),
        typeof(int), typeof(uint),
        typeof(long), typeof(ulong),
        typeof(float), typeof(double), typeof(decimal),
        typeof(DateTime), typeof(DateTimeOffset),
        typeof(DateOnly), typeof(TimeOnly),
        typeof(TimeSpan),
        typeof(Guid),
    ];

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    protected override void OnInitialized()
    {
        _columns = BuildColumns();
        _serverDataDelegate = LoadServerData;
    }

    // ── Column detection ──────────────────────────────────────────────────────

    private List<ColumnDefinition<TDto>> BuildColumns() => typeof(TDto)
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanRead && IsScalarProperty(p) && !ExcludedProperties.Contains(p.Name))
            .Select(p =>
            {
                var underlyingType = Nullable.GetUnderlyingType(p.PropertyType) ?? p.PropertyType;
                return new ColumnDefinition<TDto>
                {
                    Header = ResolveHeader(p.Name),
                    FieldName = ToCamelCase(p.Name),
                    SortFieldName = p.Name,
                    PropertyType = underlyingType,
                    Sortable = true,
                    GetDisplayValue = dto => FormatValue(p.GetValue(dto), underlyingType),
                };
            })
            .ToList();

    private string ResolveHeader(string propertyName)
    {
        if (ColumnHeaders is not null && ColumnHeaders.TryGetValue(propertyName, out var custom))
        {
            return custom;
        }
        // "FirstName" → "First Name"
        return Regex.Replace(propertyName, "([A-Z])", " $1").TrimStart();
    }

    private static bool IsScalarProperty(PropertyInfo p)
    {
        var type = Nullable.GetUnderlyingType(p.PropertyType) ?? p.PropertyType;
        return ScalarTypes.Contains(type) || type.IsEnum;
    }

    // ── Server-side data loading ──────────────────────────────────────────────

    private async Task<TableData<TDto>> LoadServerData(TableState state, CancellationToken ct)
    {
        _loading = true;
        _errorMessage = string.Empty;

        try
        {
            var skip = state.Page * state.PageSize;
            var query = BuildBatchedGraphQLQuery(skip, state.PageSize, state.SortLabel, state.SortDirection, _activeSearchTerm);

            var (items, totalCount) = await GraphQLService.QueryWithCountAsync<TDto>(
                GraphQLEndpoint, query, EntityName, BearerToken, ct);

            return new TableData<TDto> { Items = items, TotalItems = totalCount };
        }
        catch (Exception ex)
        {
            _errorMessage = $"Fehler beim Laden der Daten: {ex.Message}";
            return new TableData<TDto> { Items = [], TotalItems = 0 };
        }
        finally
        {
            _loading = false;
        }
    }

    // ── GraphQL query builder ─────────────────────────────────────────────────

    /// <summary>
    /// Builds a single GraphQL request that fetches both the paged list and the total count
    /// (with the same optional where-filter applied to both fields).
    /// </summary>
    private string BuildBatchedGraphQLQuery(int skip, int take, string? sortLabel, SortDirection sortDirection, string activeSearch)
    {
        var fields = string.Join("\n    ", _columns.Select(c => c.FieldName));
        var whereClause = BuildWhereClause(activeSearch);

        // ── list arguments ────────────────────────────────────────────────────
        var listArgs = new List<string> { $"skip: {skip}", $"take: {take}" };

        if (!string.IsNullOrWhiteSpace(sortLabel))
        {
            var dir = sortDirection == SortDirection.Descending ? "DESC" : "ASC";
            listArgs.Add($"order: [{{ field: \"{sortLabel}\", direction: {dir} }}]");
        }

        if (whereClause is not null)
        {
            listArgs.Add(whereClause);
        }

        // ── count arguments (same where, no skip/take/order) ──────────────────
        var countArgs = whereClause is not null ? $"({whereClause})" : string.Empty;

        return $@"{{
  {EntityName}({string.Join(", ", listArgs)}) {{
    {fields}
  }}
  {EntityName}Count{countArgs}
}}";
    }

    /// <summary>
    /// Builds a HotChocolate-compatible <c>where: { or: […] }</c> clause.
    /// <list type="bullet">
    ///   <item>String columns → <c>contains</c></item>
    ///   <item>Numeric / Guid columns → <c>eq</c> (only when the search term is parseable as that type)</item>
    /// </list>
    /// Returns <c>null</c> when no matching conditions can be built.
    /// </summary>
    private string? BuildWhereClause(string search)
    {
        if (string.IsNullOrWhiteSpace(search))
        {
            return null;
        }

        var conditions = new List<string>();
        var escaped = EscapeGraphQLString(search);

        foreach (var col in _columns)
        {
            if (col.PropertyType == typeof(string))
            {
                conditions.Add($"{{ {col.FieldName}: {{ contains: \"{escaped}\" }} }}");
            }
            else
            {
                var eqValue = TryBuildEqLiteral(search, col.PropertyType);
                if (eqValue is not null)
                {
                    conditions.Add($"{{ {col.FieldName}: {{ eq: {eqValue} }} }}");
                }
            }
        }

        return conditions.Count == 0 ? null
            : $"where: {{ or: [{string.Join(", ", conditions)}] }}";
    }

    /// <summary>
    /// Tries to produce a GraphQL literal value for an <c>eq</c> filter.
    /// Returns <c>null</c> when <paramref name="search"/> cannot be parsed as <paramref name="type"/>.
    /// </summary>
    private static string? TryBuildEqLiteral(string search, Type type)
    {
        if (type == typeof(Guid))
        {
            return Guid.TryParse(search, out var g) ? $"\"{g}\"" : null;
        }

        if (type == typeof(bool))
        {
            return bool.TryParse(search, out var b) ? b.ToString().ToLowerInvariant() : null;
        }

        if (type == typeof(int) || type == typeof(short) || type == typeof(byte) || type == typeof(sbyte) || type == typeof(ushort) || type == typeof(uint))
        {
            return int.TryParse(search, out var i) ? i.ToString() : null;
        }

        if (type == typeof(long) || type == typeof(ulong))
        {
            return long.TryParse(search, out var l) ? l.ToString() : null;
        }

        if (type == typeof(decimal))
        {
            return decimal.TryParse(search, System.Globalization.NumberStyles.Number,
                System.Globalization.CultureInfo.InvariantCulture, out var d)
                ? d.ToString(System.Globalization.CultureInfo.InvariantCulture) : null;
        }

        return type == typeof(double)
            ? double.TryParse(search, System.Globalization.NumberStyles.Number,
                System.Globalization.CultureInfo.InvariantCulture, out var db)
                ? db.ToString(System.Globalization.CultureInfo.InvariantCulture) : null
            : type == typeof(float)
            ? float.TryParse(search, System.Globalization.NumberStyles.Number,
                System.Globalization.CultureInfo.InvariantCulture, out var f)
                ? f.ToString(System.Globalization.CultureInfo.InvariantCulture) : null
            : null;
    }

    private static string EscapeGraphQLString(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            sb.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ => ch.ToString(),
            });
        }

        return sb.ToString();
    }

    // ── Formatting helpers ────────────────────────────────────────────────────

    private static string FormatValue(object? value, Type type)
    {
        if (value is null)
        {
            return string.Empty;
        }

        if (type == typeof(DateTime))
        {
            return ((DateTime)value).ToString("dd.MM.yyyy HH:mm");
        }

        if (type == typeof(DateTimeOffset))
        {
            return ((DateTimeOffset)value).ToString("dd.MM.yyyy HH:mm");
        }

        if (type == typeof(DateOnly))
        {
            return ((DateOnly)value).ToString("dd.MM.yyyy");
        }

        if (type == typeof(TimeOnly))
        {
            return ((TimeOnly)value).ToString("HH:mm");
        }

        if (type == typeof(TimeSpan))
        {
            return ((TimeSpan)value).ToString(@"hh\:mm\:ss");
        }

        if (type == typeof(bool))
        {
            return (bool)value ? "Ja" : "Nein";
        }

        return type == typeof(decimal)
            ? ((decimal)value).ToString("N2")
            : type == typeof(double)
            ? ((double)value).ToString("N2")
            : type == typeof(float) ? ((float)value).ToString("N2") : value.ToString() ?? string.Empty;
    }

    private static string ToCamelCase(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name[1..];

    // ── Public API ────────────────────────────────────────────────────────────

    private async Task OnSearchTermChanged(string value)
    {
        _searchTerm = value;
        await _debounceCts.CancelAsync();
        _debounceCts = new CancellationTokenSource();
        try
        {
            await Task.Delay(500, _debounceCts.Token);
            _activeSearchTerm = _searchTerm;
            await ReloadTable();
        }
        catch (OperationCanceledException) { }
    }

    private async Task OnSearchCleared()
    {
        _searchTerm = string.Empty;
        _activeSearchTerm = string.Empty;
        await _debounceCts.CancelAsync();
        await ReloadTable();
    }

    /// <summary>Programmatically refreshes the table data from the server.</summary>
    public async Task ReloadTable()
    {
        if (_table is not null)
        {
            await _table.ReloadServerData();
        }
    }
}
