<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>
      Abstractions package for CleanCodeJN.GenericApis.
    </Description>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Jörg Nieveler</Authors>
    <Title>CleanCodeJN.GenericAPIs.Abstractions</Title>
    <PackageTags>Abstractions;CRUD;WebAPI;ASP.NET;MinimalAPIs;MVC;Controllers;IOSP;EntityFramework;MediatR;CQRS;CleanCode;DDD;Mapster;Commands;IntegrationOperationSegregationPrinciple;GenericRepository;DotNet</PackageTags>
    <PackageReleaseNotes>ICleanCodeMapper abstraction backed by Mapster.</PackageReleaseNotes>
    <RepositoryUrl>https://github.com/decius999/CleanCodeJN-Generic-Apis</RepositoryUrl>
    <PackageProjectUrl>https://github.com/decius999/CleanCodeJN-Generic-Apis</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>CleanCodeJN-Icon-Green.png</PackageIcon>
    <VersionPrefix>4.1.0</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CleanCodeJN-Icon-Green.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
